### ISSUE TITLE
A warning message in the search page

### ISSUE THREAD

**Issue by saifulkhan** [ScottishCovidResponse/rampvis-ui#104]
There is a warning message on the search page. To reproduce it just search for 'oxford' on the search page then it should appear in the chrome dev console.

The error log:
`react_devtools_backend.js:2540 Warning: validateDOMNesting(...): <hr> cannot appear as a descendant of <p>.
    at hr
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-99289b21.browser.esm.js:55:66)
    at Divider (webpack-internal:///./node_modules/@mui/material/Divider/Divider.js:156:83)
    at span
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-99289b21.browser.esm.js:55:66)
    at Typography (webpack-internal:///./node_modules/@mui/material/Typography/Typography.js:101:88)
    at p
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-99289b21.browser.esm.js:55:66)
    at Typography (webpack-internal:///./node_modules/@mui/material/Typography/Typography.js:101:88)
    at div
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-99289b21.browser.esm.js:55:66)
    at ListItemText (webpack-internal:///./node_modules/@mui/material/ListItemText/ListItemText.js:75:82)
    at li
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-99289b21.browser.esm.js:55:66)
    at ListItem (webpack-internal:///./node_modules/@mui/material/ListItem/ListItem.js:164:83)
    at ul
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-99289b21.browser.esm.js:55:66)
    at List (webpack-internal:///./node_modules/@mui/material/List/List.js:66:82)
    at div
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-99289b21.browser.esm.js:55:66)
    at Box (webpack-internal:///./node_modules/@mui/system/esm/createBox.js:33:72)
    at SearchResultView (webpack-internal:///./src/components/search/SearchResultView.tsx:37:23)
    at div
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-99289b21.browser.esm.js:55:66)
    at Container (webpack-internal:///./node_modules/@mui/material/Container/Container.js:93:83)
    at div
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-99289b21.browser.esm.js:55:66)
    at Box (webpack-internal:///./node_modules/@mui/system/esm/createBox.js:33:72)
    at PageSearch (webpack-internal:///./src/pages/search.tsx:94:85)
    at div
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-99289b21.browser.esm.js:55:66)
    at div
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-99289b21.browser.esm.js:55:66)
    at div
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-99289b21.browser.esm.js:55:66)
    at div
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-99289b21.browser.esm.js:55:66)
    at DashboardLayout (webpack-internal:///./src/components/dashboard-layout/DashboardLayout.tsx:68:26)
    at InnerThemeProvider (webpack-internal:///./node_modules/@material-ui/core/styles/ThemeProvider.js:21:70)
    at ThemeProvider (webpack-internal:///./node_modules/@material-ui/private-theming/ThemeProvider/ThemeProvider.js:47:5)
    at ThemeProvider (webpack-internal:///./node_modules/@material-ui/core/styles/ThemeProvider.js:41:5)
    at AuthProviderJWT (webpack-internal:///./src/contexts/AuthProviderJWT.tsx:139:26)
    at SettingsProvider (webpack-internal:///./src/contexts/SettingsContext.tsx:61:26)
    at LocalizationProvider (webpack-internal:///./node_modules/@material-ui/lab/LocalizationProvider/LocalizationProvider.js:21:5)
    at StyledEngineProvider (webpack-internal:///./node_modules/@material-ui/styled-engine/StyledEngineProvider/StyledEngineProvider.js:26:5)
    at r (webpack-internal:///./node_modules/react-helmet-async/lib/index.module.js:16:6680)
    at MyApp (webpack-internal:///./src/pages/_app.tsx:87:27)
    at StyleRegistry (webpack-internal:///./node_modules/styled-jsx/dist/stylesheet-registry.js:231:34)
    at ErrorBoundary (webpack-internal:///./node_modules/@next/react-dev-overlay/lib/internal/ErrorBoundary.js:26:47)
    at ReactDevOverlay (webpack-internal:///./node_modules/@next/react-dev-overlay/lib/internal/ReactDevOverlay.js:90:23)
    at Container (webpack-internal:///./node_modules/next/dist/client/index.js:305:9)
    at AppContainer (webpack-internal:///./node_modules/next/dist/client/index.js:745:26)
    at Root (webpack-internal:///./node_modules/next/dist/client/index.js:866:27)
overrideMethod @ react_devtools_backend.js:2540
printWarning @ react-dom.development.js?ac89:67
error @ react-dom.development.js?ac89:43
validateDOMNesting @ react-dom.development.js?ac89:10083
createInstance @ react-dom.development.js?ac89:10181
completeWork @ react-dom.development.js?ac89:19464
completeUnitOfWork @ react-dom.development.js?ac89:22815
performUnitOfWork @ react-dom.development.js?ac89:22787
workLoopSync @ react-dom.development.js?ac89:22707
renderRootSync @ react-dom.development.js?ac89:22670
performSyncWorkOnRoot @ react-dom.development.js?ac89:22293
eval @ react-dom.development.js?ac89:11327
unstable_runWithPriority @ scheduler.development.js?bcd2:468
runWithPriority$1 @ react-dom.development.js?ac89:11276
flushSyncCallbackQueueImpl @ react-dom.development.js?ac89:11322
flushSyncCallbackQueue @ react-dom.development.js?ac89:11309
scheduleUpdateOnFiber @ react-dom.development.js?ac89:21893
dispatchAction @ react-dom.development.js?ac89:16139
_callee$ @ search.tsx?a8f2:40
tryCatch @ runtime.js?c56e:45
invoke @ runtime.js?c56e:274
prototype.<computed> @ runtime.js?c56e:97
asyncGeneratorStep @ search.tsx?a8f2:9
_next @ search.tsx?a8f2:9
Promise.then (async)
asyncGeneratorStep @ search.tsx?a8f2:9
_next @ search.tsx?a8f2:9
Promise.then (async)
asyncGeneratorStep @ search.tsx?a8f2:9
_next @ search.tsx?a8f2:9
eval @ search.tsx?a8f2:9
eval @ search.tsx?a8f2:9
_callee$ @ search.tsx?a8f2:49
tryCatch @ runtime.js?c56e:45
invoke @ runtime.js?c56e:274
prototype.<computed> @ runtime.js?c56e:97
asyncGeneratorStep @ search.tsx?a8f2:9
_next @ search.tsx?a8f2:9
eval @ search.tsx?a8f2:9
eval @ search.tsx?a8f2:9
onClick @ SearchBar.tsx?a2c3:64
callCallback @ react-dom.development.js?ac89:3945
invokeGuardedCallbackDev @ react-dom.development.js?ac89:3994
invokeGuardedCallback @ react-dom.development.js?ac89:4056
invokeGuardedCallbackAndCatchFirstError @ react-dom.development.js?ac89:4070
executeDispatch @ react-dom.development.js?ac89:8243
processDispatchQueueItemsInOrder @ react-dom.development.js?ac89:8275
processDispatchQueue @ react-dom.development.js?ac89:8288
dispatchEventsForPlugins @ react-dom.development.js?ac89:8299
eval @ react-dom.development.js?ac89:8508
batchedEventUpdates$1 @ react-dom.development.js?ac89:22396
batchedEventUpdates @ react-dom.development.js?ac89:3745
dispatchEventForPluginEventSystem @ react-dom.development.js?ac89:8507
attemptToDispatchEvent @ react-dom.development.js?ac89:6005
dispatchEvent @ react-dom.development.js?ac89:5924
unstable_runWithPriority @ scheduler.development.js?bcd2:468
runWithPriority$1 @ react-dom.development.js?ac89:11276
discreteUpdates$1 @ react-dom.development.js?ac89:22413
discreteUpdates @ react-dom.development.js?ac89:3756
dispatchDiscreteEvent @ react-dom.development.js?ac89:5889
Show 28 more frames
SearchResultView.tsx?c721:46 `

**Comment by kachkaev** [comment]
Closed by #119
